<?php
/**
 * Bulletin.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\BulletinModule\Form\Type\Field;

use RK\BulletinModule\Form\Type\Field\Base\AbstractAutoCompletionRelationType;

/**
 * Auto completion relation field type implementation class.
 */
class AutoCompletionRelationType extends AbstractAutoCompletionRelationType
{
    // feel free to add your customisation here
}
