<?php
/**
 * Bulletin.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\BulletinModule\Form\DataTransformer;

use RK\BulletinModule\Form\DataTransformer\Base\AbstractAutoCompletionRelationTransformer;

/**
 * Auto completion relation transformer implementation class.
 *
 * This data transformer identifiers chosen by an auto completion functionality.
 */
class AutoCompletionRelationTransformer extends AbstractAutoCompletionRelationTransformer
{
    // feel free to add your customisation here
}
