<?php
/**
 * Bulletin.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\BulletinModule\Form\Type\QuickNavigation;

use RK\BulletinModule\Form\Type\QuickNavigation\Base\AbstractNoticeQuickNavType;

/**
 * Notice quick navigation form type implementation class.
 */
class NoticeQuickNavType extends AbstractNoticeQuickNavType
{
    // feel free to extend the base form type class here
}
