<?php
/**
 * Bulletin.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\BulletinModule\Base;

/**
 * Events definition base class.
 */
abstract class AbstractBulletinEvents
{
    /**
     * The rkbulletinmodule.notice_post_load event is thrown when notices
     * are loaded from the database.
     *
     * The event listener receives an
     * RK\BulletinModule\Event\FilterNoticeEvent instance.
     *
     * @see RK\BulletinModule\Listener\EntityLifecycleListener::postLoad()
     * @var string
     */
    const NOTICE_POST_LOAD = 'rkbulletinmodule.notice_post_load';
    
    /**
     * The rkbulletinmodule.notice_pre_persist event is thrown before a new notice
     * is created in the system.
     *
     * The event listener receives an
     * RK\BulletinModule\Event\FilterNoticeEvent instance.
     *
     * @see RK\BulletinModule\Listener\EntityLifecycleListener::prePersist()
     * @var string
     */
    const NOTICE_PRE_PERSIST = 'rkbulletinmodule.notice_pre_persist';
    
    /**
     * The rkbulletinmodule.notice_post_persist event is thrown after a new notice
     * has been created in the system.
     *
     * The event listener receives an
     * RK\BulletinModule\Event\FilterNoticeEvent instance.
     *
     * @see RK\BulletinModule\Listener\EntityLifecycleListener::postPersist()
     * @var string
     */
    const NOTICE_POST_PERSIST = 'rkbulletinmodule.notice_post_persist';
    
    /**
     * The rkbulletinmodule.notice_pre_remove event is thrown before an existing notice
     * is removed from the system.
     *
     * The event listener receives an
     * RK\BulletinModule\Event\FilterNoticeEvent instance.
     *
     * @see RK\BulletinModule\Listener\EntityLifecycleListener::preRemove()
     * @var string
     */
    const NOTICE_PRE_REMOVE = 'rkbulletinmodule.notice_pre_remove';
    
    /**
     * The rkbulletinmodule.notice_post_remove event is thrown after an existing notice
     * has been removed from the system.
     *
     * The event listener receives an
     * RK\BulletinModule\Event\FilterNoticeEvent instance.
     *
     * @see RK\BulletinModule\Listener\EntityLifecycleListener::postRemove()
     * @var string
     */
    const NOTICE_POST_REMOVE = 'rkbulletinmodule.notice_post_remove';
    
    /**
     * The rkbulletinmodule.notice_pre_update event is thrown before an existing notice
     * is updated in the system.
     *
     * The event listener receives an
     * RK\BulletinModule\Event\FilterNoticeEvent instance.
     *
     * @see RK\BulletinModule\Listener\EntityLifecycleListener::preUpdate()
     * @var string
     */
    const NOTICE_PRE_UPDATE = 'rkbulletinmodule.notice_pre_update';
    
    /**
     * The rkbulletinmodule.notice_post_update event is thrown after an existing new notice
     * has been updated in the system.
     *
     * The event listener receives an
     * RK\BulletinModule\Event\FilterNoticeEvent instance.
     *
     * @see RK\BulletinModule\Listener\EntityLifecycleListener::postUpdate()
     * @var string
     */
    const NOTICE_POST_UPDATE = 'rkbulletinmodule.notice_post_update';
    
    /**
     * The rkbulletinmodule.picture_post_load event is thrown when pictures
     * are loaded from the database.
     *
     * The event listener receives an
     * RK\BulletinModule\Event\FilterPictureEvent instance.
     *
     * @see RK\BulletinModule\Listener\EntityLifecycleListener::postLoad()
     * @var string
     */
    const PICTURE_POST_LOAD = 'rkbulletinmodule.picture_post_load';
    
    /**
     * The rkbulletinmodule.picture_pre_persist event is thrown before a new picture
     * is created in the system.
     *
     * The event listener receives an
     * RK\BulletinModule\Event\FilterPictureEvent instance.
     *
     * @see RK\BulletinModule\Listener\EntityLifecycleListener::prePersist()
     * @var string
     */
    const PICTURE_PRE_PERSIST = 'rkbulletinmodule.picture_pre_persist';
    
    /**
     * The rkbulletinmodule.picture_post_persist event is thrown after a new picture
     * has been created in the system.
     *
     * The event listener receives an
     * RK\BulletinModule\Event\FilterPictureEvent instance.
     *
     * @see RK\BulletinModule\Listener\EntityLifecycleListener::postPersist()
     * @var string
     */
    const PICTURE_POST_PERSIST = 'rkbulletinmodule.picture_post_persist';
    
    /**
     * The rkbulletinmodule.picture_pre_remove event is thrown before an existing picture
     * is removed from the system.
     *
     * The event listener receives an
     * RK\BulletinModule\Event\FilterPictureEvent instance.
     *
     * @see RK\BulletinModule\Listener\EntityLifecycleListener::preRemove()
     * @var string
     */
    const PICTURE_PRE_REMOVE = 'rkbulletinmodule.picture_pre_remove';
    
    /**
     * The rkbulletinmodule.picture_post_remove event is thrown after an existing picture
     * has been removed from the system.
     *
     * The event listener receives an
     * RK\BulletinModule\Event\FilterPictureEvent instance.
     *
     * @see RK\BulletinModule\Listener\EntityLifecycleListener::postRemove()
     * @var string
     */
    const PICTURE_POST_REMOVE = 'rkbulletinmodule.picture_post_remove';
    
    /**
     * The rkbulletinmodule.picture_pre_update event is thrown before an existing picture
     * is updated in the system.
     *
     * The event listener receives an
     * RK\BulletinModule\Event\FilterPictureEvent instance.
     *
     * @see RK\BulletinModule\Listener\EntityLifecycleListener::preUpdate()
     * @var string
     */
    const PICTURE_PRE_UPDATE = 'rkbulletinmodule.picture_pre_update';
    
    /**
     * The rkbulletinmodule.picture_post_update event is thrown after an existing new picture
     * has been updated in the system.
     *
     * The event listener receives an
     * RK\BulletinModule\Event\FilterPictureEvent instance.
     *
     * @see RK\BulletinModule\Listener\EntityLifecycleListener::postUpdate()
     * @var string
     */
    const PICTURE_POST_UPDATE = 'rkbulletinmodule.picture_post_update';
    
    /**
     * The rkbulletinmodule.event_post_load event is thrown when events
     * are loaded from the database.
     *
     * The event listener receives an
     * RK\BulletinModule\Event\FilterEventEvent instance.
     *
     * @see RK\BulletinModule\Listener\EntityLifecycleListener::postLoad()
     * @var string
     */
    const EVENT_POST_LOAD = 'rkbulletinmodule.event_post_load';
    
    /**
     * The rkbulletinmodule.event_pre_persist event is thrown before a new event
     * is created in the system.
     *
     * The event listener receives an
     * RK\BulletinModule\Event\FilterEventEvent instance.
     *
     * @see RK\BulletinModule\Listener\EntityLifecycleListener::prePersist()
     * @var string
     */
    const EVENT_PRE_PERSIST = 'rkbulletinmodule.event_pre_persist';
    
    /**
     * The rkbulletinmodule.event_post_persist event is thrown after a new event
     * has been created in the system.
     *
     * The event listener receives an
     * RK\BulletinModule\Event\FilterEventEvent instance.
     *
     * @see RK\BulletinModule\Listener\EntityLifecycleListener::postPersist()
     * @var string
     */
    const EVENT_POST_PERSIST = 'rkbulletinmodule.event_post_persist';
    
    /**
     * The rkbulletinmodule.event_pre_remove event is thrown before an existing event
     * is removed from the system.
     *
     * The event listener receives an
     * RK\BulletinModule\Event\FilterEventEvent instance.
     *
     * @see RK\BulletinModule\Listener\EntityLifecycleListener::preRemove()
     * @var string
     */
    const EVENT_PRE_REMOVE = 'rkbulletinmodule.event_pre_remove';
    
    /**
     * The rkbulletinmodule.event_post_remove event is thrown after an existing event
     * has been removed from the system.
     *
     * The event listener receives an
     * RK\BulletinModule\Event\FilterEventEvent instance.
     *
     * @see RK\BulletinModule\Listener\EntityLifecycleListener::postRemove()
     * @var string
     */
    const EVENT_POST_REMOVE = 'rkbulletinmodule.event_post_remove';
    
    /**
     * The rkbulletinmodule.event_pre_update event is thrown before an existing event
     * is updated in the system.
     *
     * The event listener receives an
     * RK\BulletinModule\Event\FilterEventEvent instance.
     *
     * @see RK\BulletinModule\Listener\EntityLifecycleListener::preUpdate()
     * @var string
     */
    const EVENT_PRE_UPDATE = 'rkbulletinmodule.event_pre_update';
    
    /**
     * The rkbulletinmodule.event_post_update event is thrown after an existing new event
     * has been updated in the system.
     *
     * The event listener receives an
     * RK\BulletinModule\Event\FilterEventEvent instance.
     *
     * @see RK\BulletinModule\Listener\EntityLifecycleListener::postUpdate()
     * @var string
     */
    const EVENT_POST_UPDATE = 'rkbulletinmodule.event_post_update';
    
}
