<?php
/**
 * Bulletin.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\BulletinModule\Base;

use Doctrine\DBAL\Connection;
use RuntimeException;
use Zikula\Core\AbstractExtensionInstaller;
use Zikula_Workflow_Util;
use Zikula\CategoriesModule\Entity\CategoryRegistryEntity;

/**
 * Installer base class.
 */
abstract class AbstractBulletinModuleInstaller extends AbstractExtensionInstaller
{
    /**
     * Install the RKBulletinModule application.
     *
     * @return boolean True on success, or false
     *
     * @throws RuntimeException Thrown if database tables can not be created or another error occurs
     */
    public function install()
    {
        $logger = $this->container->get('logger');
        $userName = $this->container->get('zikula_users_module.current_user')->get('uname');
    
        // Check if upload directories exist and if needed create them
        try {
            $container = $this->container;
            $uploadHelper = new \RK\BulletinModule\Helper\UploadHelper($container->get('translator.default'), $container->get('session'), $container->get('logger'), $container->get('zikula_users_module.current_user'), $container->get('zikula_extensions_module.api.variable'), $container->getParameter('datadir'));
            $uploadHelper->checkAndCreateAllUploadFolders();
        } catch (\Exception $e) {
            $this->addFlash('error', $e->getMessage());
            $logger->error('{app}: User {user} could not create upload folders during installation. Error details: {errorMessage}.', ['app' => 'RKBulletinModule', 'user' => $userName, 'errorMessage' => $e->getMessage()]);
        
            return false;
        }
        // create all tables from according entity definitions
        try {
            $this->schemaTool->create($this->listEntityClasses());
        } catch (\Exception $e) {
            $this->addFlash('error', $this->__('Doctrine Exception') . ': ' . $e->getMessage());
            $logger->error('{app}: Could not create the database tables during installation. Error details: {errorMessage}.', ['app' => 'RKBulletinModule', 'errorMessage' => $e->getMessage()]);
    
            return false;
        }
    
        // set up all our vars with initial values
        $this->setVar('teaserLength', '5000');
        $this->setVar('teaserDisplayLength', '250');
        $this->setVar('descriptionLength', 0);
        $this->setVar('showCounter', true);
        $this->setVar('noticeEntriesPerPage', '10');
        $this->setVar('linkOwnNoticesOnAccountPage', true);
        $this->setVar('pictureEntriesPerPage', '10');
        $this->setVar('linkOwnPicturesOnAccountPage', true);
        $this->setVar('eventEntriesPerPage', '10');
        $this->setVar('linkOwnEventsOnAccountPage', true);
        $this->setVar('enableShrinkingForNoticeImage', false);
        $this->setVar('shrinkWidthNoticeImage', '800');
        $this->setVar('shrinkHeightNoticeImage', '600');
        $this->setVar('thumbnailModeNoticeImage',  'inset' );
        $this->setVar('thumbnailWidthNoticeImageView', '32');
        $this->setVar('thumbnailHeightNoticeImageView', '24');
        $this->setVar('thumbnailWidthNoticeImageDisplay', '240');
        $this->setVar('thumbnailHeightNoticeImageDisplay', '180');
        $this->setVar('thumbnailWidthNoticeImageEdit', '240');
        $this->setVar('thumbnailHeightNoticeImageEdit', '180');
        $this->setVar('enableShrinkingForPictureImage', false);
        $this->setVar('shrinkWidthPictureImage', '800');
        $this->setVar('shrinkHeightPictureImage', '600');
        $this->setVar('thumbnailModePictureImage',  'inset' );
        $this->setVar('thumbnailWidthPictureImageView', '32');
        $this->setVar('thumbnailHeightPictureImageView', '24');
        $this->setVar('thumbnailWidthPictureImageDisplay', '240');
        $this->setVar('thumbnailHeightPictureImageDisplay', '180');
        $this->setVar('thumbnailWidthPictureImageEdit', '240');
        $this->setVar('thumbnailHeightPictureImageEdit', '180');
        $this->setVar('enabledFinderTypes', [ 'notice' ,  'picture' ,  'event' ]);
    
        $categoryRegistryIdsPerEntity = [];
    
        // add default entry for category registry (property named Main)
        $categoryHelper = new \RK\BulletinModule\Helper\CategoryHelper(
            $this->container->get('translator.default'),
            $this->container->get('session'),
            $this->container->get('request_stack'),
            $logger,
            $this->container->get('zikula_users_module.current_user'),
            $this->container->get('zikula_categories_module.api.category_registry'),
            $this->container->get('zikula_categories_module.api.category_permission')
        );
        $categoryGlobal = $this->container->get('zikula_categories_module.api.category')->getCategoryByPath('/__SYSTEM__/Modules/Global');
    
        $registry = new CategoryRegistryEntity();
        $registry->setModname('RKBulletinModule');
        $registry->setEntityname('NoticeEntity');
        $registry->setProperty($categoryHelper->getPrimaryProperty('Notice'));
        $registry->setCategory_Id($categoryGlobal['id']);
    
        try {
            $entityManager = $this->container->get('doctrine.orm.default_entity_manager');
            $entityManager->persist($registry);
            $entityManager->flush();
        } catch (\Exception $e) {
            $this->addFlash('error', $this->__f('Error! Could not create a category registry for the %entity% entity.', ['%entity%' => 'notice']));
            $logger->error('{app}: User {user} could not create a category registry for {entities} during installation. Error details: {errorMessage}.', ['app' => 'RKBulletinModule', 'user' => $userName, 'entities' => 'notices', 'errorMessage' => $e->getMessage()]);
        }
        $categoryRegistryIdsPerEntity['notice'] = $registry->getId();
    
        $registry = new CategoryRegistryEntity();
        $registry->setModname('RKBulletinModule');
        $registry->setEntityname('EventEntity');
        $registry->setProperty($categoryHelper->getPrimaryProperty('Event'));
        $registry->setCategory_Id($categoryGlobal['id']);
    
        try {
            $entityManager = $this->container->get('doctrine.orm.default_entity_manager');
            $entityManager->persist($registry);
            $entityManager->flush();
        } catch (\Exception $e) {
            $this->addFlash('error', $this->__f('Error! Could not create a category registry for the %entity% entity.', ['%entity%' => 'event']));
            $logger->error('{app}: User {user} could not create a category registry for {entities} during installation. Error details: {errorMessage}.', ['app' => 'RKBulletinModule', 'user' => $userName, 'entities' => 'events', 'errorMessage' => $e->getMessage()]);
        }
        $categoryRegistryIdsPerEntity['event'] = $registry->getId();
    
        // create the default data
        $this->createDefaultData($categoryRegistryIdsPerEntity);
    
        // install subscriber hooks
        $this->hookApi->installSubscriberHooks($this->bundle->getMetaData());
    
        // initialisation successful
        return true;
    }
    
    /**
     * Upgrade the RKBulletinModule application from an older version.
     *
     * If the upgrade fails at some point, it returns the last upgraded version.
     *
     * @param integer $oldVersion Version to upgrade from
     *
     * @return boolean True on success, false otherwise
     *
     * @throws RuntimeException Thrown if database tables can not be updated
     */
    public function upgrade($oldVersion)
    {
    /*
        $logger = $this->container->get('logger');
    
        // Upgrade dependent on old version number
        switch ($oldVersion) {
            case '1.0.0':
                // do something
                // ...
                // update the database schema
                try {
                    $this->schemaTool->update($this->listEntityClasses());
                } catch (\Exception $e) {
                    $this->addFlash('error', $this->__('Doctrine Exception') . ': ' . $e->getMessage());
                    $logger->error('{app}: Could not update the database tables during the upgrade. Error details: {errorMessage}.', ['app' => 'RKBulletinModule', 'errorMessage' => $e->getMessage()]);
    
                    return false;
                }
        }
    
        // Note there are several helpers available for making migrating your extension from Zikula 1.3 to 1.4 easier.
        // The following convenience methods are each responsible for a single aspect of upgrading to Zikula 1.4.x.
    
        // here is a possible usage example
        // of course 1.2.3 should match the number you used for the last stable 1.3.x module version.
        /* if ($oldVersion = '1.2.3') {
            // rename module for all modvars
            $this->updateModVarsTo14();
            
            // update extension information about this app
            $this->updateExtensionInfoFor14();
            
            // rename existing permission rules
            $this->renamePermissionsFor14();
            
            // rename existing category registries
            $this->renameCategoryRegistriesFor14();
            
            // rename all tables
            $this->renameTablesFor14();
            
            // remove event handler definitions from database
            $this->dropEventHandlersFromDatabase();
            
            // update module name in the hook tables
            $this->updateHookNamesFor14();
            
            // update module name in the workflows table
            $this->updateWorkflowsFor14();
        } * /
    */
    
        // update successful
        return true;
    }
    
    /**
     * Renames the module name for variables in the module_vars table.
     */
    protected function updateModVarsTo14()
    {
        $dbName = $this->getDbName();
        $conn = $this->getConnection();
    
        $conn->executeQuery("
            UPDATE $dbName.module_vars
            SET modname = 'RKBulletinModule'
            WHERE modname = 'Bulletin';
        ");
    }
    
    /**
     * Renames this application in the core's extensions table.
     */
    protected function updateExtensionInfoFor14()
    {
        $conn = $this->getConnection();
        $dbName = $this->getDbName();
    
        $conn->executeQuery("
            UPDATE $dbName.modules
            SET name = 'RKBulletinModule',
                directory = 'RK/BulletinModule'
            WHERE name = 'Bulletin';
        ");
    }
    
    /**
     * Renames all permission rules stored for this app.
     */
    protected function renamePermissionsFor14()
    {
        $conn = $this->getConnection();
        $dbName = $this->getDbName();
    
        $componentLength = strlen('Bulletin') + 1;
    
        $conn->executeQuery("
            UPDATE $dbName.group_perms
            SET component = CONCAT('RKBulletinModule', SUBSTRING(component, $componentLength))
            WHERE component LIKE 'Bulletin%';
        ");
    }
    
    /**
     * Renames all category registries stored for this app.
     */
    protected function renameCategoryRegistriesFor14()
    {
        $conn = $this->getConnection();
        $dbName = $this->getDbName();
    
        $componentLength = strlen('Bulletin') + 1;
    
        $conn->executeQuery("
            UPDATE $dbName.categories_registry
            SET modname = CONCAT('RKBulletinModule', SUBSTRING(modname, $componentLength))
            WHERE modname LIKE 'Bulletin%';
        ");
    }
    
    /**
     * Renames all (existing) tables of this app.
     */
    protected function renameTablesFor14()
    {
        $conn = $this->getConnection();
        $dbName = $this->getDbName();
    
        $oldPrefix = 'bull_';
        $oldPrefixLength = strlen($oldPrefix);
        $newPrefix = 'rk_bull_';
    
        $sm = $conn->getSchemaManager();
        $tables = $sm->listTables();
        foreach ($tables as $table) {
            $tableName = $table->getName();
            if (substr($tableName, 0, $oldPrefixLength) != $oldPrefix) {
                continue;
            }
    
            $newTableName = str_replace($oldPrefix, $newPrefix, $tableName);
    
            $conn->executeQuery("
                RENAME TABLE $dbName.$tableName
                TO $dbName.$newTableName;
            ");
        }
    }
    
    /**
     * Removes event handlers from database as they are now described by service definitions and managed by dependency injection.
     */
    protected function dropEventHandlersFromDatabase()
    {
        \EventUtil::unregisterPersistentModuleHandlers('Bulletin');
    }
    
    /**
     * Updates the module name in the hook tables.
     */
    protected function updateHookNamesFor14()
    {
        $conn = $this->getConnection();
        $dbName = $this->getDbName();
    
        $conn->executeQuery("
            UPDATE $dbName.hook_area
            SET owner = 'RKBulletinModule'
            WHERE owner = 'Bulletin';
        ");
    
        $componentLength = strlen('subscriber.bulletin') + 1;
        $conn->executeQuery("
            UPDATE $dbName.hook_area
            SET areaname = CONCAT('subscriber.rkbulletinmodule', SUBSTRING(areaname, $componentLength))
            WHERE areaname LIKE 'subscriber.bulletin%';
        ");
    
        $conn->executeQuery("
            UPDATE $dbName.hook_binding
            SET sowner = 'RKBulletinModule'
            WHERE sowner = 'Bulletin';
        ");
    
        $conn->executeQuery("
            UPDATE $dbName.hook_runtime
            SET sowner = 'RKBulletinModule'
            WHERE sowner = 'Bulletin';
        ");
    
        $componentLength = strlen('bulletin') + 1;
        $conn->executeQuery("
            UPDATE $dbName.hook_runtime
            SET eventname = CONCAT('rkbulletinmodule', SUBSTRING(eventname, $componentLength))
            WHERE eventname LIKE 'bulletin%';
        ");
    
        $conn->executeQuery("
            UPDATE $dbName.hook_subscriber
            SET owner = 'RKBulletinModule'
            WHERE owner = 'Bulletin';
        ");
    
        $componentLength = strlen('bulletin') + 1;
        $conn->executeQuery("
            UPDATE $dbName.hook_subscriber
            SET eventname = CONCAT('rkbulletinmodule', SUBSTRING(eventname, $componentLength))
            WHERE eventname LIKE 'bulletin%';
        ");
    }
    
    /**
     * Updates the module name in the workflows table.
     */
    protected function updateWorkflowsFor14()
    {
        $conn = $this->getConnection();
        $dbName = $this->getDbName();
    
        $conn->executeQuery("
            UPDATE $dbName.workflows
            SET module = 'RKBulletinModule'
            WHERE module = 'Bulletin';
        ");
    }
    
    /**
     * Returns connection to the database.
     *
     * @return Connection the current connection
     */
    protected function getConnection()
    {
        $entityManager = $this->container->get('doctrine.orm.default_entity_manager');
        $connection = $entityManager->getConnection();
    
        return $connection;
    }
    
    /**
     * Returns the name of the default system database.
     *
     * @return string the database name
     */
    protected function getDbName()
    {
        return $this->container->getParameter('database_name');
    }
    
    /**
     * Uninstall RKBulletinModule.
     *
     * @return boolean True on success, false otherwise
     *
     * @throws RuntimeException Thrown if database tables or stored workflows can not be removed
     */
    public function uninstall()
    {
        $logger = $this->container->get('logger');
    
        // delete stored object workflows
        $result = Zikula_Workflow_Util::deleteWorkflowsForModule('RKBulletinModule');
        if (false === $result) {
            $this->addFlash('error', $this->__f('An error was encountered while removing stored object workflows for the %extension% extension.', ['%extension%' => 'RKBulletinModule']));
            $logger->error('{app}: Could not remove stored object workflows during uninstallation.', ['app' => 'RKBulletinModule']);
    
            return false;
        }
    
        try {
            $this->schemaTool->drop($this->listEntityClasses());
        } catch (\Exception $e) {
            $this->addFlash('error', $this->__('Doctrine Exception') . ': ' . $e->getMessage());
            $logger->error('{app}: Could not remove the database tables during uninstallation. Error details: {errorMessage}.', ['app' => 'RKBulletinModule', 'errorMessage' => $e->getMessage()]);
    
            return false;
        }
    
        // uninstall subscriber hooks
        $this->hookApi->uninstallSubscriberHooks($this->bundle->getMetaData());
    
        // remove all module vars
        $this->delVars();
    
        // remove category registry entries
        $categoryRegistryApi = $this->container->get('zikula_categories_module.api.category_registry');
        // assume that not more than five registries exist
        for ($i = 1; $i <= 5; $i++) {
            $categoryRegistryApi->deleteRegistry('RKBulletinModule');
        }
    
        // remove all thumbnails
        $manager = $this->container->get('systemplugin.imagine.manager');
        $manager->setModule('RKBulletinModule');
        $manager->cleanupModuleThumbs();
    
        // remind user about upload folders not being deleted
        $uploadPath = $this->container->getParameter('datadir') . '/RKBulletinModule/';
        $this->addFlash('status', $this->__f('The upload directories at "%path%" can be removed manually.', ['%path%' => $uploadPath]));
    
        // uninstallation successful
        return true;
    }
    
    /**
     * Build array with all entity classes for RKBulletinModule.
     *
     * @return array list of class names
     */
    protected function listEntityClasses()
    {
        $classNames = [];
        $classNames[] = 'RK\BulletinModule\Entity\NoticeEntity';
        $classNames[] = 'RK\BulletinModule\Entity\NoticeTranslationEntity';
        $classNames[] = 'RK\BulletinModule\Entity\NoticeCategoryEntity';
        $classNames[] = 'RK\BulletinModule\Entity\PictureEntity';
        $classNames[] = 'RK\BulletinModule\Entity\EventEntity';
        $classNames[] = 'RK\BulletinModule\Entity\EventTranslationEntity';
        $classNames[] = 'RK\BulletinModule\Entity\EventCategoryEntity';
    
        return $classNames;
    }
    
    /**
     * Create the default data for RKBulletinModule.
     *
     * @param array $categoryRegistryIdsPerEntity List of category registry ids
     *
     * @return void
     */
    protected function createDefaultData($categoryRegistryIdsPerEntity)
    {
        $entityManager = $this->container->get('doctrine.orm.default_entity_manager');
        $logger = $this->container->get('logger');
        $request = $this->container->get('request_stack')->getCurrentRequest();
        
        $entityClass = 'RK\BulletinModule\Entity\NoticeEntity';
        $entityManager->getRepository($entityClass)->truncateTable($logger);
        $entityClass = 'RK\BulletinModule\Entity\PictureEntity';
        $entityManager->getRepository($entityClass)->truncateTable($logger);
        $entityClass = 'RK\BulletinModule\Entity\EventEntity';
        $entityManager->getRepository($entityClass)->truncateTable($logger);
    }
}
