<?php
/**
 * Bulletin.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\BulletinModule\Event;

use RK\BulletinModule\Event\Base\AbstractFilterEventEvent;

/**
 * Event implementation class for filtering event processing.
 */
class FilterEventEvent extends AbstractFilterEventEvent
{
    // feel free to extend the event class here
}
