<?php
/**
 * Bulletin.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\BulletinModule\Form\Handler\Event;

use RK\BulletinModule\Form\Handler\Event\Base\AbstractEditHandler;

/**
 * This handler class handles the page events of the Form called by the rKBulletinModule_event_edit() function.
 * It aims on the event object type.
 */
class EditHandler extends AbstractEditHandler
{
    // feel free to extend the base handler class here
}
