services:
    # Custom validators
    rk_bulletin_module.validator.list_entry.validator:
        class: RK\BulletinModule\Validator\Constraints\ListEntryValidator
        arguments:
            - "@translator.default"
            - "@rk_bulletin_module.listentries_helper"
        tags:
            - { name: validator.constraint_validator, alias: rk_bulletin_module.validator.list_entry.validator }
