<?php
/**
 * Bulletin.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\BulletinModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use RK\BulletinModule\Entity\PictureEntity;

/**
 * Event base class for filtering picture processing.
 */
class AbstractFilterPictureEvent extends Event
{
    /**
     * @var PictureEntity Reference to treated entity instance.
     */
    protected $picture;

    /**
     * @var array Entity change set for preUpdate events.
     */
    protected $entityChangeSet = [];

    /**
     * FilterPictureEvent constructor.
     *
     * @param PictureEntity $picture Processed entity
     * @param array $entityChangeSet Change set for preUpdate events
     */
    public function __construct(PictureEntity $picture, $entityChangeSet = [])
    {
        $this->picture = $picture;
        $this->entityChangeSet = $entityChangeSet;
    }

    /**
     * Returns the entity.
     *
     * @return PictureEntity
     */
    public function getPicture()
    {
        return $this->picture;
    }

    /**
     * Returns the change set.
     *
     * @return array
     */
    public function getEntityChangeSet()
    {
        return $this->entityChangeSet;
    }
}
