<?php
/**
 * Bulletin.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\BulletinModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use RK\BulletinModule\Entity\EventEntity;

/**
 * Event base class for filtering event processing.
 */
class AbstractFilterEventEvent extends Event
{
    /**
     * @var EventEntity Reference to treated entity instance.
     */
    protected $event;

    /**
     * @var array Entity change set for preUpdate events.
     */
    protected $entityChangeSet = [];

    /**
     * FilterEventEvent constructor.
     *
     * @param EventEntity $event Processed entity
     * @param array $entityChangeSet Change set for preUpdate events
     */
    public function __construct(EventEntity $event, $entityChangeSet = [])
    {
        $this->event = $event;
        $this->entityChangeSet = $entityChangeSet;
    }

    /**
     * Returns the entity.
     *
     * @return EventEntity
     */
    public function getEvent()
    {
        return $this->event;
    }

    /**
     * Returns the change set.
     *
     * @return array
     */
    public function getEntityChangeSet()
    {
        return $this->entityChangeSet;
    }
}
