<?php
/**
 * Bulletin.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\BulletinModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use RK\BulletinModule\Entity\NoticeEntity;

/**
 * Event base class for filtering notice processing.
 */
class AbstractFilterNoticeEvent extends Event
{
    /**
     * @var NoticeEntity Reference to treated entity instance.
     */
    protected $notice;

    /**
     * @var array Entity change set for preUpdate events.
     */
    protected $entityChangeSet = [];

    /**
     * FilterNoticeEvent constructor.
     *
     * @param NoticeEntity $notice Processed entity
     * @param array $entityChangeSet Change set for preUpdate events
     */
    public function __construct(NoticeEntity $notice, $entityChangeSet = [])
    {
        $this->notice = $notice;
        $this->entityChangeSet = $entityChangeSet;
    }

    /**
     * Returns the entity.
     *
     * @return NoticeEntity
     */
    public function getNotice()
    {
        return $this->notice;
    }

    /**
     * Returns the change set.
     *
     * @return array
     */
    public function getEntityChangeSet()
    {
        return $this->entityChangeSet;
    }
}
