<?php
/**
 * Bulletin.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\BulletinModule\Entity;

use RK\BulletinModule\Entity\Base\AbstractNoticeTranslationEntity as BaseEntity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity extension domain class storing notice translations.
 *
 * This is the concrete translation class for notice entities.
 *
 * @ORM\Entity(repositoryClass="RK\BulletinModule\Entity\Repository\NoticeTranslationRepository")
 * @ORM\Table(name="rk_bull_notice_translation",
 *     indexes={
 *         @ORM\Index(name="translations_lookup_idx", columns={
 *             "locale", "object_class", "foreign_key"
 *         })
 *     }
 * )
 */
class NoticeTranslationEntity extends BaseEntity
{
    // feel free to add your own methods here
}
