<?php
/**
 * Bulletin.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\BulletinModule\Entity;

use RK\BulletinModule\Entity\Base\AbstractPictureEntity as BaseEntity;
use Doctrine\ORM\Mapping as ORM;

/**
 * Entity class that defines the entity structure and behaviours.
 *
 * This is the concrete entity class for picture entities.
 * @ORM\Entity(repositoryClass="RK\BulletinModule\Entity\Repository\PictureRepository")
 * @ORM\Table(name="rk_bull_picture",
 *     indexes={
 *         @ORM\Index(name="workflowstateindex", columns={"workflowState"})
 *     }
 * )
 */
class PictureEntity extends BaseEntity
{
    // feel free to add your own methods here
}
