<?php
/**
 * Bulletin.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\BulletinModule\Form\Type;

use RK\BulletinModule\Form\Type\Base\AbstractEventType;

/**
 * Event editing form type implementation class.
 */
class EventType extends AbstractEventType
{
    // feel free to extend the event editing form type class here
}
