<?php
/**
 * Bulletin.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\BulletinModule\Form\Type\Finder;

use RK\BulletinModule\Form\Type\Finder\Base\AbstractNoticeFinderType;

/**
 * Notice finder form type implementation class.
 */
class NoticeFinderType extends AbstractNoticeFinderType
{
    // feel free to extend the base form type class here
}
