<?php
/**
 * Bulletin.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\BulletinModule\Helper;

use RK\BulletinModule\Helper\Base\AbstractModelHelper;

/**
 * Helper implementation class for model layer methods.
 */
class ModelHelper extends AbstractModelHelper
{
    // feel free to add your own convenience methods here
}
