<?php
/**
 * Bulletin.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (http://modulestudio.de).
 */

namespace RK\BulletinModule\Entity\Base;

use Doctrine\ORM\Mapping as ORM;
use Zikula\CategoriesModule\Entity\AbstractCategoryAssignment;

/**
 * Entity extension domain class storing notice categories.
 *
 * This is the base category class for notice entities.
 */
abstract class AbstractNoticeCategoryEntity extends AbstractCategoryAssignment
{
    /**
     * @ORM\ManyToOne(targetEntity="\RK\BulletinModule\Entity\NoticeEntity", inversedBy="categories")
     * @ORM\JoinColumn(name="entityId", referencedColumnName="id")
     * @var \RK\BulletinModule\Entity\NoticeEntity
     */
    protected $entity;
    
    /**
     * Get reference to owning entity.
     *
     * @return \RK\BulletinModule\Entity\NoticeEntity
     */
    public function getEntity()
    {
        return $this->entity;
    }
    
    /**
     * Set reference to owning entity.
     *
     * @param \RK\BulletinModule\Entity\NoticeEntity $entity
     */
    public function setEntity(/*\RK\BulletinModule\Entity\NoticeEntity */$entity)
    {
        $this->entity = $entity;
    }
}
